---

- name: Manage SKS Keyserver
  hosts: 'debops_sks'
  sudo: True

  roles:
#    - role: debops.sks
#      tags: [ 'role::sks', 'sks' ]


- name: Manage iPXE configuration files
  hosts: 'debops_ipxe'
  sudo: True

  roles:
#    - role: debops.ipxe
#      tags: [ 'role::ipxe', 'ipxe' ]


- name: Manage BoxBackup service
  hosts: 'debops_boxbackup'
  sudo: True

  roles:
#    - role: debops.boxbackup
#      tags: [ 'role::boxbackup', 'boxbackup' ]


- name: Manage rsnapshot service
  hosts: 'debops_rsnapshot:debops_rsnapshot_rsync'
  sudo: True

  roles:
#    - role: debops.rsnapshot
#      tags: [ 'role::rsnapshot', 'rsnapshot' ]


- name: Manage Mailman service
  hosts: 'debops_mailman'
  sudo: True

  roles:
#    - role: debops.mailman
#      tags: [ 'role::mailman', 'mailman' ]


- name: Manage LibreNMS
  hosts: 'debops_librenms'
  sudo: True

  roles:
#    - role: debops.librenms
#      tags: [ 'role::librenms' ]


- name: Manage DokuWiki
  hosts: 'debops_dokuwiki'
  sudo: True

  roles:
#    - role: debops.dokuwiki
#      tags: [ 'role::dokuwiki', 'dokuwiki' ]


- name: Manage Etherpad service
  hosts: 'debops_etherpad'
  sudo: True

  roles:
#    - role: debops.etherpad
#      tags: [ 'role::etherpad', 'etherpad' ]


- name: Manage Preseed server
  hosts: 'debops_preseed'
  sudo: True

  roles:
#    - role: debops.preseed
#      tags: [ 'role::preseed', 'preseed' ]


- name: Manage ownCloud service
  hosts: 'debops_owncloud'
  sudo: True

  roles:
#    - role: debops.owncloud
#      tags: [ 'role::owncloud', 'owncloud' ]


- name: Manage phpIPAM service
  hosts: 'debops_phpipam'
  sudo: True

  roles:
#    - role: debops.phpipam
#      tags: [ 'role::phpipam', 'phpipam' ]


- name: Manage RStudio Server
  hosts: 'debops_rstudio_server'
  sudo: True

  roles:
#    - role: debops.rstudio_server
#      tags: [ 'role::rstudio_server', 'rstudio_server' ]


- name: Manage GitLab service
  hosts: 'debops_gitlab'
  sudo: True

  roles:
#    - role: debops.gitlab
#      tags: [ 'role::gitlab', 'gitlab' ]

- name: Manage GitLab CI service
  hosts: 'debops_gitlab_ci'
  sudo: True

  roles:
#    - role: debops.gitlab_ci
#      tags: [ 'role::gitlab_ci', 'gitlab_ci' ]

- name: Manage GitLab CI Runner service
  hosts: 'debops_gitlab_ci_runner'
  sudo: True

  roles:
#    - role: debops.gitlab_ci_runner
#      tags: [ 'role::gitlab_ci_runner', 'gitlab_ci_runner' ]


- name: Install DebOps recursively
  hosts: 'debops_recursively'
  sudo: True

  roles:
#    - role: debops.debops
#      tags: [ 'role::debops', 'debops' ]

- name: Manage Stash service
  hosts: 'stash'
  sudo: True

  roles:
    - { role: stash, tags: stash }

- name: Manage Jira service
  hosts: 'jira'
  sudo: True

  roles:
    - { role: jira, tags: jira }

- name: Manage Confluence service
  hosts: 'confluence'
  sudo: True

  roles:
    - { role: confluence, tags: confluence }

- name: Manage bimpoto service
  hosts: 'bimproto'
  sudo: True

  roles:
    - { role: bimproto, tags: bimproto }
