---

- name: Manage GitLab service
  hosts: 'debops_gitlab'
  sudo: True

  roles:
    - role: debops.gitlab
      tags: [ 'role::gitlab', 'gitlab' ]

- name: Manage GitLab CI service
  hosts: 'debops_gitlab_ci'
  sudo: True

  roles:
    - role: debops.gitlab_ci
      tags: [ 'role::gitlab_ci', 'gitlab_ci' ]

- name: Install Desktop system
  hosts: 'desktop'
  sudo: True

  roles:
    - role: desktop
      tags: [ 'role::desktop', 'desktop' ]
