---

- name: Configure HWRaid support
  hosts: 'debops_hwraid'
  sudo: True

  roles:

    - { role: debops.hwraid, tags: hwraid }

- name: Configure Laptop utilities
  hosts: 'laptop'
  sudo: True

  roles:

    - { role: laptop, tags: laptop }

- name: Configure Printer
  hosts: 'printer'
  sudo: True

  roles:

    - { role: printer, tags: printer }
