---

- name: Configure HWRaid support
  hosts: 'debops_hwraid'
  sudo: True

  roles:

    - { role: debops.hwraid, tags: hwraid }


- name: Configure GRUB
  hosts: 'debops_grub'
  sudo: True

  roles:

    - role: debops.grub
      tags: [ 'role::grub' ]


- name: Configure Laptop utilities
  hosts: 'laptop'
  sudo: True

  roles:

    - { role: laptop, tags: laptop }

- name: Configure Printer
  hosts: 'printer'
  sudo: True

  roles:

    - { role: printer, tags: printer }

- name: Configure Router
  hosts: 'router'
  gather_facts: False
  roles:

    - { role: router, tags: router }
