---

- name: Configure internal networks
  hosts: 'debops_subnetwork'
  sudo: True

  roles:
    - role: debops.subnetwork
      tags: [ 'role::subnetwork', 'subnetwork' ]


- name: Configure Router Advertisement Daemon
  hosts: 'debops_radvd'
  sudo: True

  roles:
    - role: debops.radvd
      tags: [ 'role::radvd', 'radvd' ]


- name: Manage ISC DHCP server
  hosts: 'debops_dhcpd'
  sudo: True

  roles:
    - role: debops.dhcpd
      tags: [ 'role::dhcpd', 'dhcpd' ]


- name: Configure dnsmasq
  hosts: debops_dnsmasq
  sudo: True

  roles:
    - role: debops.dnsmasq
      tags: [ 'role::dnsmasq', 'dnsmasq' ]


- name: Configure tinc VPN
  hosts: debops_tinc
  sudo: True

  roles:
    - role: debops.tinc
      tags: [ 'role::tinc', 'tinc' ]


- name: Configure stunnel
  hosts: debops_stunnel
  sudo: True

  roles:
    - role: debops.stunnel
      tags: [ 'role::stunnel', 'stunnel' ]

