---

- name: Configure internal networks
  hosts: 'debops_subnetwork'
  sudo: True

  roles:
    - role: debops.subnetwork
      tags: [ 'role::subnetwork', 'subnetwork' ]


- name: Configure dnsmasq
  hosts: debops_dnsmasq
  sudo: True

  roles:
    - role: debops.dnsmasq
      tags: [ 'role::dnsmasq', 'dnsmasq' ]


