---

- name: Manage nginx server
  hosts: 'debops_nginx'
  sudo: True

  roles:
    - role: debops.nginx
      tags: [ 'role::nginx', 'nginx' ]


- name: Manage Samba service
  hosts: 'debops_samba'
  sudo: True

  roles:
    - role: debops.samba
      tags: [ 'role::samba', 'samba' ]


- name: Manage PostgreSQL server
  hosts: 'debops_postgresql_server'
  sudo: True

  roles:
    - role: debops.postgresql_server
      tags: [ 'role::postgresql_server' ]


- name: Manage PostgreSQL client
  hosts: 'debops_postgresql'
  sudo: True

  roles:
    - role: debops.postgresql
      tags: [ 'role::postgresql', 'postgresql' ]


- name: Manage fail2ban service
  hosts: 'debops_fail2ban'
  sudo: True

  roles:
    - role: debops.fail2ban
      tags: [ 'role::fail2ban', 'fail2ban' ]

