---

- name: Manage users with git-shell accounts
  hosts: 'debops_gitusers'
  sudo: True

  roles:
    - role: debops.gitusers
      tags: [ 'role::gitusers', 'gitusers' ]

    - role: debops.sshkeys
      tags: [ 'role::sshkeys', 'sshkeys' ]


- name: Configure ZFS filesystems and settings
  hosts: 'zfs'
  sudo: True

  roles:

    - { role: zfs, tags: zfs }

