---

- name: Manage users with git-shell accounts
  hosts: 'debops_gitusers'
  sudo: True

  roles:
    - { role: debops.gitusers, tags: gitusers }
    - { role: debops.sshkeys,  tags: sshkeys }


- name: Manage users with SFTPonly accounts
  hosts: 'debops_sftpusers'
  sudo: True

  roles:
    - { role: debops.sftpusers, tags: sftpusers }
    - { role: debops.sshkeys,   tags: sshkeys }


- name: Manage OpenLDAP server
  hosts: 'debops_slapd'
  sudo: True

  roles:
#    - { role: debops.slapd, tags: slapd }


- name: Configure Logical Volume Manager
  hosts: 'debops_lvm'
  sudo: True

  roles:
    - { role: debops.lvm, tags: lvm }


- name: Configure iSCSI Initiator
  hosts: 'debops_iscsi'
  sudo: True

  roles:
    - { role: debops.iscsi, tags: iscsi }


- name: Manage NFSv3 services
  hosts: 'debops_nfs'
  sudo: True

  roles:
#    - { role: debops.nfs, tags: nfs }


- name: Configure ZFS filesystems and settings
  hosts: 'zfs'
  sudo: True

  roles:

    - { role: zfs, tags: zfs }

